# Generated by Django 3.1.6 on 2021-09-06 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nmr_orden', models.CharField(max_length=50, verbose_name='nombre')),
                ('date_time_orden', models.DateField()),
                ('state', models.CharField(choices=[('solicitada', 'solicitada'), ('aprobada', 'aprobada'), ('anulada', 'anulada')], max_length=150)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client')),
            ],
        ),
    ]
