# Generated by Django 3.1.6 on 2021-09-06 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='nombre')),
                ('address', models.CharField(max_length=50, verbose_name='direccion')),
                ('cell', models.CharField(max_length=50, verbose_name='telefono')),
                ('nationality', models.CharField(max_length=50, verbose_name='nacionalidad')),
                ('email', models.EmailField(max_length=254, verbose_name='correo')),
            ],
        ),
    ]
